// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"deployment-test/controller"
	"deployment-test/helper"
	"deployment-test/repository"
	"deployment-test/service"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
)

// Injectors from injector.go:

func IntitializedServer() (*http.Server, func(), error) {
	db, cleanup, err := helper.NewDb()
	if err != nil {
		return nil, nil, err
	}
	repositoryImpl := repository.NewRepositoryImpl()
	serviceImpl := service.NewService(db, repositoryImpl)
	controllerImpl := controller.NewController(serviceImpl)
	router := NewRouter(controllerImpl)
	server := NewServer(router)
	return server, func() {
		cleanup()
	}, nil
}

// injector.go:

var ServerSet = wire.NewSet(repository.NewRepositoryImpl, wire.Bind(new(repository.Repository), new(*repository.RepositoryImpl)), service.NewService, wire.Bind(new(service.Service), new(*service.ServiceImpl)), controller.NewController, wire.Bind(new(controller.Controller), new(*controller.ControllerImpl)), NewServer, wire.Bind(new(http.Handler), new(*httprouter.Router)), NewRouter, helper.NewDb)
